### ISSUE TITLE
请问一下，是否分钟k线数据只能获取两个月的？

### ISSUE THREAD

**Issue by winglight** [Micro-sheep/efinance#1]
```
df = ef.stock.get_quote_history(['000001', '000002'], beg='19000101', end='20500101', klt=5)
```
这个代码返回的只有2021-05-31之后的数据，之前的数据要怎么获取呢？

**Comment by Micro-sheep** [comment]
5分钟k线确实只能获取最近2个月的，再早的话没法获取了，因为东方财富那边的免费接口没有提供更早数据了。如果是日、月、年数据就不会有限制。如果有一天能找到不限分钟数据时间段的接口，我再做修改吧。或者你看到哪个网站可以免费看任意时间段分钟线数据也可以告诉我，效果可以的话我把它加到这个项目里面。

**Comment by winglight** [comment]
我就是在找可以获取历史分钟k线的方法才发现你这个库的，之前tdx是可以的，但是现在限制了只能取半年了。

**Comment by Micro-sheep** [comment]
> 我就是在找可以获取历史分钟k线的方法才发现你这个库的，之前tdx是可以的，但是现在限制了只能取半年了。

tdx 这个库好像是调用通达信的接口，我有空试试看是不是通达信本身做了限制。
