### ISSUE TITLE
get_latest_quote(stock_code)有自动去重功能吗？构建的代码列表输出少一些

### ISSUE THREAD

**Issue by xuezhai-f** [Micro-sheep/efinance#103]
使用这个函数get_latest_quote(stock_code)，比如构建了38个代码，其中有2个重复的，仅能输出37个数据。有办法取消这个去重功能吗

**Comment by Micro-sheep** [comment]
我实现这个函数的时候，没有做去除重复的功能。有可能是服务端那边自动去重了。不过我想了解一下，你是因为什么，需要取消自动去重呢？

**Comment by xuezhai-f** [comment]
好吧，我不同账户有相同的票，xlwings输出到Excel时就对不上了

**Comment by xuezhai-f** [comment]
嗯 可以重构df，就是稍微麻烦一点
