### ISSUE TITLE
期货数据缺少广州期货交易所

### ISSUE THREAD

**Issue by lededev** [Micro-sheep/efinance#105]
目前模块还不支持广州期货交易所吧，希望能够增加支持
```
>>> import efinance as ef
>>> G_info = ef.futures.get_futures_base_info()
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('上')])
286
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('郑')])
244
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('大')])
262
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('中')])
73
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('广')])
0
```

**Comment by Micro-sheep** [comment]
> 

这个目前可以通过下面的代码来实现
```python
import efinance.common.config as config
import efinance as ef


def add_futures_market(market_number: str, market_name: str):
    config.MARKET_NUMBER_DICT[market_number] = market_name
    old = config.FS_DICT['futures']
    config.FS_DICT['futures'] = ','.join(
        (old, f'm:{market_number}'))
    config.FS_DICT['futures'] = ','.join(
        set(config.FS_DICT['futures'].split(',')))


add_futures_market('225', '广期所')
df = ef.futures.get_realtime_quotes()

print(len([i for i, v in enumerate(df['市场类型']) if v.startswith('广')]))

```

**Comment by Micro-sheep** [comment]
> 目前模块还不支持广州期货交易所吧，希望能够增加支持
> 
> ```
> >>> import efinance as ef
> >>> G_info = ef.futures.get_futures_base_info()
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('上')])
> 286
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('郑')])
> 244
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('大')])
> 262
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('中')])
> 73
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('广')])
> 0
> ```

大概在今天下午，会更新一个版本，增加你说的功能。

**Comment by Micro-sheep** [comment]
> 目前模块还不支持广州期货交易所吧，希望能够增加支持
> 
> ```
> >>> import efinance as ef
> >>> G_info = ef.futures.get_futures_base_info()
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('上')])
> 286
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('郑')])
> 244
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('大')])
> 262
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('中')])
> 73
> >>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('广')])
> 0
> ```

已更新，使用 `pip` 更新 `efinance` 到 `v0.5.0` 即可。

或者通过下面的命令来更新
```bash
pip install git+https://github.com/Micro-sheep/efinance
```

**Comment by lededev** [comment]
更新到v0.5.0可以了，非常感谢！
```
>>> import efinance as ef
>>> G_info = ef.futures.get_futures_base_info()
>>> len([i for i, v in enumerate(G_info['市场类型']) if v.startswith('广')])
7

```
