### ISSUE TITLE
想知道各分段成交数据

### ISSUE THREAD

**Issue by weijiuyang** [Micro-sheep/efinance#112]
就比如股票，想知道当天 各价格的成交量，比如买一，卖一的成交量

**Comment by Micro-sheep** [comment]
下面是一个例子
```
import efinance as ef

df = ef.stock.get_deal_detail('600519')
df
```
![image](https://user-images.githubusercontent.com/56242295/221387997-e9564d29-efc1-4eea-a23f-9ea36e85f028.png)

**Comment by weijiuyang** [comment]
啊不是每个时间点成交
是当天汇总的各金额成交量
![IMG_F7B7CC4E9FFE-1](https://user-images.githubusercontent.com/34874738/221395266-64f4112d-4631-4fe2-b4ef-909af2bce427.jpeg)

**Comment by Micro-sheep** [comment]
> 啊不是每个时间点成交
> 
> 是当天汇总的各金额成交量
> 
> ![IMG_F7B7CC4E9FFE-1](https://user-images.githubusercontent.com/34874738/221395266-64f4112d-4631-4fe2-b4ef-909af2bce427.jpeg)
> 
> 

基于这个对成交价格分组求和即可。

**Comment by weijiuyang** [comment]
啊也对hh，是的，，感谢

**Comment by weijiuyang** [comment]
thanks!!!so much
