### ISSUE TITLE
怎么看A股竞价相关的数据，比如开盘成交量

### ISSUE THREAD

**Issue by Note-Liu** [Micro-sheep/efinance#115]

**Comment by Micro-sheep** [comment]
用 `efinance.stock.get_deal_detail` 这个函数获取最新交易日秒级别的成交数据，然后截取成交时间早于 `09:30` 的最后一行数据来运算

```python
import efinance as ef

df = ef.stock.get_deal_detail('600519')
df[df['时间'] < '09:30'].iloc[-1]
```
![image](https://user-images.githubusercontent.com/56242295/226583124-138329e2-0a97-4b76-a277-e8a13bd7460c.png)
![image](https://user-images.githubusercontent.com/56242295/226583312-94ca99d0-b00a-4685-90b1-6e02c1ebeda5.png)

**Comment by Note-Liu** [comment]
Thanks !
