### ISSUE TITLE
大佬未来可以提供一个api给出可供查询的指数列表吗

### ISSUE THREAD

**Issue by weijiuyang** [Micro-sheep/efinance#119]
<img width="451" alt="image" src="https://user-images.githubusercontent.com/34874738/230724184-01f8d7fd-be99-4f2e-a86f-19a450793066.png">
在函数get_numbers中，提供的参数可以是指数名称或者指数代码。但是不知道那些指数的成分股信息可以获得，我去东方财富查有些指数代码查不到，希望可以提供一个指数列表

**Comment by Micro-sheep** [comment]
可以通过下面的方式来查询指数列表

```python
import efinance as ef
df = ef.stock.get_realtime_quotes('沪深系列指数')
df
```
![image](https://user-images.githubusercontent.com/56242295/230724845-58450931-45cc-422c-9395-633f4bb1dd5f.png)

**Comment by weijiuyang** [comment]
多谢多谢！！！大佬太强了也
