### ISSUE TITLE
个别美股获取不了或者获取的数据有误

### ISSUE THREAD

**Issue by henry991217** [Micro-sheep/efinance#128]
我在使用获取历史数据的接口函数efinance.stock.get_quote_history(stock_codes: Union[str, List[str]], beg: str = '19000101', end: str = '20500101', klt: int = 101, fqt: int = 1, **kwargs)时发现个别美股如MRK(默沙东)、PLD(安博)输入美股代码后无法获取到相应数据；个别股如PG（宝洁）输入美股代码获取到的是AAPL(苹果)的数据，以上三个代码好像只能通过输入中文字符来获取 请问有可能通过美股股票代码获取到这些股票的历史数据吗？

**Comment by Micro-sheep** [comment]
对于这种有冲突的情况，可以参考这两个个 issue：https://github.com/Micro-sheep/efinance/issues/30 https://github.com/Micro-sheep/efinance/issues/74 

参考完之后，到 https://github.com/Micro-sheep/efinance/blob/main/efinance/common/config.py#L13 去寻找对应的前缀。

**Comment by henry991217** [comment]
> 对于这种有冲突的情况，可以参考这两个个 issue：#30 #74
> 
> 参考完之后，到 https://github.com/Micro-sheep/efinance/blob/main/efinance/common/config.py#L13 去寻找对应的前缀。

明白！感谢大佬回复
