### ISSUE TITLE
docker容器中调用存在SSLError错误

### ISSUE THREAD

**Issue by chunhuasun** [Micro-sheep/efinance#15]
# 股票代码
stock_code = '300610'
# 开始日期
beg = '20210101'
# 结束日期
end = '20210818'
# 测试代码
df_history = ef.stock.get_quote_history(stock_code, beg=beg, end=end)
本机调用正常

发布到docker容器后，
访问https请求时，报出SSl认证失败
![image](https://user-images.githubusercontent.com/22069787/129828548-b0f50165-71dc-4cd9-8022-da3a2346eba1.png)
这种情况如何处理呐

**Comment by Micro-sheep** [comment]
> # 股票代码
> 
> stock_code = '300610'
> 
> # 开始日期
> 
> beg = '20210101'
> 
> # 结束日期
> 
> end = '20210818'
> 
> # 测试代码
> 
> df_history = ef.stock.get_quote_history(stock_code, beg=beg, end=end)
> 
> 本机调用正常
> 
> 
> 
> 发布到docker容器后，
> 
> 访问https请求时，报出SSl认证失败
> 
> ![image](https://user-images.githubusercontent.com/22069787/129828548-b0f50165-71dc-4cd9-8022-da3a2346eba1.png)
> 
> 这种情况如何处理呐

尝试安装 python 3.7 版本。如果不行的话，建议在 docker 里面装 miniconda 然后再使用 miniconda 的 python 环境。

**Comment by Micro-sheep** [comment]
> # 股票代码
> stock_code = '300610'
> 
> # 开始日期
> beg = '20210101'
> 
> # 结束日期
> end = '20210818'
> 
> # 测试代码
> df_history = ef.stock.get_quote_history(stock_code, beg=beg, end=end)
> 本机调用正常
> 
> 发布到docker容器后，
> 访问https请求时，报出SSl认证失败
> ![image](https://user-images.githubusercontent.com/22069787/129828548-b0f50165-71dc-4cd9-8022-da3a2346eba1.png)
> 这种情况如何处理呐

实测在 `docker `里面使用 `miniconda` 则没有这个问题。安装 `miniconda `的方法如下（Linux 系统,，当然你也可以选其他方法）
```bash
# 下载
wget https://repo.anaconda.com/miniconda/Miniconda3-latest-Linux-x86_64.sh
# 安装（这里会出现交互选项，全部填默认即可，如果有 yes 就选 yes）
bash Miniconda3-latest-Linux-x86_64.sh
#  更新配置以可以使用 conda、python、pip
source ~/.bashrc

```
经过以上操作，你将可以在此环境下使用 `python` 以及 `pip`

**Comment by chunhuasun** [comment]
好的，感谢感谢，我去试试

**Comment by Micro-sheep** [comment]
> 好的，感谢感谢，我去试试

今天刚在 README.md 里面添加使用 docker 安装的教程，参考一下应该可以解决直接使用 python 镜像而出现的SSL Error 的问题。
