### ISSUE TITLE
请问免费端口的查询量是怎样的？

### ISSUE THREAD

**Issue by six7ths** [Micro-sheep/efinance#16]
比如每天查询多少条？ 或者怎么样的？ 不知道有没有说明

**Comment by Micro-sheep** [comment]
> 比如每天查询多少条？ 或者怎么样的？ 不知道有没有说明

查询次数以及速度无限制。查询条数默认尽可能地多，具体有多少，可以看 API 文档里面的实例代码。

**Comment by six7ths** [comment]
好的，多谢多谢
