### ISSUE TITLE
获取基金代码 有错误数据

### ISSUE THREAD

**Issue by huntergd** [Micro-sheep/efinance#17]
>>> ef.fund.get_fund_codes(ft = 'gp')
        基金代码                  基金简称
    0     003834              华夏能源革新股票
    1     005669            前海开源公用事业股票
    2     004040             金鹰医疗健康产业A
    **3     517793                 1.20%**
  
517793                 1.20%
数据有误
   
应该 把     columns = ['基金代码', '基金简称']
    results = re.findall('(\d{6}),(.*?),', response.text)
改为   
        text = text[text.index('["') + 2:text.index('"]')]
        fs = text.split('","')
        datas = {'基金代码': [], '基金简称': [], '净值': []]}
        for f in fs:
            data = f.split(',')
            datas['基金代码'].append(data[0])
            datas['基金简称'].append(data[1])

**Comment by Micro-sheep** [comment]
>  >>> ef.fund.get_fund_codes(ft = 'gp')
> 
>         基金代码                  基金简称
> 
>     0     003834              华夏能源革新股票
> 
>     1     005669            前海开源公用事业股票
> 
>     2     004040             金鹰医疗健康产业A
> 
>     **3     517793                 1.20%**
> 
>   
> 
> 517793                 1.20%
> 
> 数据有误
> 
>    
> 
> 应该 把     columns = ['基金代码', '基金简称']
> 
>     results = re.findall('(\d{6}),(.*?),', response.text)
> 
> 改为   
> 
>         text = text[text.index('["') + 2:text.index('"]')]
> 
>         fs = text.split('","')
> 
>         datas = {'基金代码': [], '基金简称': [], '净值': []]}
> 
>         for f in fs:
> 
>             data = f.split(',')
> 
>             datas['基金代码'].append(data[0])
> 
>             datas['基金简称'].append(data[1])

好 很棒啊！下个版本修复。

**Comment by Micro-sheep** [comment]
>  >>> ef.fund.get_fund_codes(ft = 'gp')
> 
>         基金代码                  基金简称
> 
>     0     003834              华夏能源革新股票
> 
>     1     005669            前海开源公用事业股票
> 
>     2     004040             金鹰医疗健康产业A
> 
>     **3     517793                 1.20%**
> 
>   
> 
> 517793                 1.20%
> 
> 数据有误
> 
>    
> 
> 应该 把     columns = ['基金代码', '基金简称']
> 
>     results = re.findall('(\d{6}),(.*?),', response.text)
> 
> 改为   
> 
>         text = text[text.index('["') + 2:text.index('"]')]
> 
>         fs = text.split('","')
> 
>         datas = {'基金代码': [], '基金简称': [], '净值': []]}
> 
>         for f in fs:
> 
>             data = f.split(',')
> 
>             datas['基金代码'].append(data[0])
> 
>             datas['基金简称'].append(data[1])

今天发布的新版本中已修复该问题。
