### ISSUE TITLE
怎么能获取股票每天的收盘价？

### ISSUE THREAD

**Issue by waynelee123** [Micro-sheep/efinance#22]
怎么能获取股票每天的收盘价？

**Comment by Micro-sheep** [comment]
详见这里面的[例子](https://github.com/Micro-sheep/efinance/blob/main/examples/stock.ipynb)，或者在 [DOCS](https://efinance.readthedocs.io) 里面搜索 "收盘" 即可看到例子。
![image](https://user-images.githubusercontent.com/56242295/133178010-4a12e9ec-25fa-4b8e-8c1f-3978e9efeb54.png)
