### ISSUE TITLE
请教一下 http://push2.eastmoney.com/ 下的接口是怎么抓到的？

### ISSUE THREAD

**Issue by axiaoxin** [Micro-sheep/efinance#24]
请教一下 http://push2.eastmoney.com/ 下的接口是怎么抓到的？我之前在ios客户端上貌似没有抓到这个域名下的接口

**Comment by Micro-sheep** [comment]
> 请教一下 http://push2.eastmoney.com/ 下的接口是怎么抓到的？我之前在ios客户端上貌似没有抓到这个域名下的接口

东方财富app客户端很多接口都不可见，但在网页版却可见。我是从天天基金以及东方财富网页版进行接口分析的，

**Comment by axiaoxin** [comment]
感谢解惑！

**Comment by money4marry** [comment]
我还一直以为是公开的api，找半天都没看见文档。
话说如果修改了接口，咱是不是也得重新分析适配
如果将来这个库发扬光大了，他们应该能注意到这部分异常流量吧，他们是个有互联网气质的券商
