### ISSUE TITLE
查询某日所有股票数据

### ISSUE THREAD

**Issue by Tinyrat** [Micro-sheep/efinance#25]
大佬，我只看到ef.stock.get_quote_history(stock_code)接口获取某个股票所有天的数据
请问怎么获取某天所有股票的数据？

**Comment by Micro-sheep** [comment]
> 大佬，我只看到ef.stock.get_quote_history(stock_code)接口获取某个股票所有天的数据
> 
> 请问怎么获取某天所有股票的数据？

正写好写完例子准备发给你你就关 issue 了，问题得到解决了吗？解决的话我就不发示例了。
