### ISSUE TITLE
请问有社区或者QQ群吗

### ISSUE THREAD

**Issue by pmgO12Y** [Micro-sheep/efinance#26]
请问有社区或者QQ群吗

**Comment by Micro-sheep** [comment]
> 请问有社区或者QQ群吗

没有社区、QQ群。如果你在使用过程中有遇到问题，可以到这里反馈。

**Comment by pmgO12Y** [comment]
> > 请问有社区或者QQ群吗
> 
> 没有社区、QQ群。如果你在使用过程中有遇到问题，可以到这里反馈。

好的，感谢提供这么好的接口
