### ISSUE TITLE
获取多只股票日线数据是否可以提速

### ISSUE THREAD

**Issue by vensentzhou** [Micro-sheep/efinance#4]
%%time
data=ef.stock.get_quote_history(hs300,beg='20210729',)

CPU times: user 12.9 s, sys: 1.3 s, total: 14.2 s
Wall time: 1min 25s

%%time
all_stock=ef.stock.get_realtime_quotes()
CPU times: user 198 ms, sys: 1.96 ms, total: 200 ms
Wall time: 816 ms

获取300指股票 一天的日线数据 需要1分25秒
获取全市场 实时数据 816ms

获取多票k线数据是否有提速的可能？

**Comment by Micro-sheep** [comment]
你在测试的时候，是把含有300个股票代码的列表传进获取历史k线数据的函数吗？

**Comment by Micro-sheep** [comment]
> %%time
> 
> data=ef.stock.get_quote_history(hs300,beg='20210729',)
> 
> 
> 
> CPU times: user 12.9 s, sys: 1.3 s, total: 14.2 s
> 
> Wall time: 1min 25s
> 
> 
> 
> %%time
> 
> all_stock=ef.stock.get_realtime_quotes()
> 
> CPU times: user 198 ms, sys: 1.96 ms, total: 200 ms
> 
> Wall time: 816 ms
> 
> 
> 
> 获取300指股票 一天的日线数据 需要1分25秒
> 
> 获取全市场 实时数据 816ms
> 
> 
> 
> 获取多票k线数据是否有提速的可能？

你试试这个，设置最大线程数，具体速度跟电脑性能以及网速关系比较大。![image](https://user-images.githubusercontent.com/56242295/127525917-9679a6e0-3e1e-4437-8e09-b501ebf7158b.png)

**Comment by vensentzhou** [comment]
我之前的测试是在dokcer 虚拟机上做的。我再试试
