### ISSUE TITLE
请问大佬，如何将获取的行情数据 保存到excel中

### ISSUE THREAD

**Issue by zhaocai-ally** [Micro-sheep/efinance#46]
请问大佬，如何将获取的行情数据 保存到excel中

**Comment by Micro-sheep** [comment]
> 请问大佬，如何将获取的行情数据 保存到excel中

得到的数据大部分是 `pandas.DataFrame`，比如你把返回的数据存到变量 `df` 里面，那么 `df.to_excel("data.xlsx")` 即可保存数据到文件 data.xlsx 里面。具体用法可以去 pandas 的官方文档里面搜索 to_excel 。

**Comment by zhaocai-ally** [comment]
非常感谢  已经解决了
