### ISSUE TITLE
获取沪深300下的全部票

### ISSUE THREAD

**Issue by tf2jaguar** [Micro-sheep/efinance#55]
- [ ] 有没有获取a股市场全部股票（只包含code，名称那种）
- [ ] 有没有获取某类型（如沪深300，中证500）下的全部票的接口呢

**Comment by Micro-sheep** [comment]
> * [ ]  有没有获取a股市场全部股票（只包含code，名称那种）
> * [ ]  有没有获取某类型（如沪深300，中证500）下的全部票的接口呢
1. 
```python
import efinance as ef
ef.stock.get_realtime_quotes('沪深A股')
```
![image](https://user-images.githubusercontent.com/56242295/171669459-df5e271b-4ea2-435a-a8f5-c78efda975be.png)
2. 
```python
import efinance as ef
ef.stock.get_members('000300')
```
![image](https://user-images.githubusercontent.com/56242295/171671024-48d9a8d7-7a4e-4406-91d8-0dc76288d197.png)


更多信息详见文档（关键词搜索）

**Comment by tf2jaguar** [comment]
好的，辛苦~
