### ISSUE TITLE
使用get_quote_history会卡住

### ISSUE THREAD

**Issue by ReBoRn8888** [Micro-sheep/efinance#58]
大佬好，想请问一下为什么我把代码放到服务器上跑，运行到get_quote_history的时候有时候会卡住不动呢？也没有任何的报错信息，我在本机跑的时候就从来没卡死过。如下图：
![image](https://user-images.githubusercontent.com/14960076/172792650-8ac0fa93-a775-4c10-8b80-2e92b5713581.png)

服务器是比较便宜的，2核4G内存，我尝试过换其他服务器跑，都会遇到这个问题

**Comment by Micro-sheep** [comment]
python 版本是多少？建议装个 miniconda，然后用里面的环境。

**Comment by Micro-sheep** [comment]
> > python 版本是多少？建议装个 miniconda，然后用里面的环境。
> 
> 
> 
> python3.8，我在服务器上就是用的anaconda里的环境

服务器网络怎么样，是国内还是国外的网络？如果是国外的，直接访问很容易卡死。你这个服务器配置跑起来，没啥问题，我也有一个配置跟你一样的。

**Comment by ReBoRn8888** [comment]
确实是国外的
![03DEE714](https://user-images.githubusercontent.com/14960076/172977900-f6a93d44-5f3c-4eae-963c-6dd305510988.png)
，大佬考不考虑把国外网络的支持也加进efinance里，现在国内我看源码是从东财的api取的数据，国外的话有没有什么类似的api可以用不

**Comment by Micro-sheep** [comment]
> 确实是国外的
> 
> ![03DEE714](https://user-images.githubusercontent.com/14960076/172977900-f6a93d44-5f3c-4eae-963c-6dd305510988.png)
> 
> ，大佬考不考虑把国外网络的支持也加进efinance里，现在国内我看源码是从东财的api取的数据，国外的话有没有什么类似的api可以用不

国外的话，可以试试 yfinance，它的数据源是雅虎财经。如果想用我这个，那你可以在服务器上面，开代理，国内网络的代理。

**Comment by ReBoRn8888** [comment]
好的，感谢大佬指点
