### ISSUE TITLE
大神，可不可以增加可转债的字段，到期时间，剩余年限这个样子。。？

### ISSUE THREAD

**Issue by cczxxc** [Micro-sheep/efinance#6]
虽然大多数都还有好几年，但也有快到期的。。比如[https://xueqiu.com/S/SZ123007](https://xueqiu.com/S/SZ123007)
看这个库用的都是东财源，东财的确是没有这一项。。雪球的有（集思录有登陆限制），
(https://xueqiu.com/hq#exchange=CN&industry=4_0&firstName=4)
不知道方不方便爬。。我水平实在有限。还是通过tqsdk接触python的，还不到1年。。

**Comment by Micro-sheep** [comment]
> 虽然大多数都还有好几年，但也有快到期的。。比如[https://xueqiu.com/S/SZ123007](https://xueqiu.com/S/SZ123007)
> 
> 看这个库用的都是东财源，东财的确是没有这一项。。雪球的有（集思录有登陆限制），
> 
> (https://xueqiu.com/hq#exchange=CN&industry=4_0&firstName=4)
> 
> 不知道方不方便爬。。我水平实在有限。还是通过tqsdk接触python的，还不到1年。。

可以，我单独帮你爬一下吧。这个好的话后续可以加到 efinance 里面。

**Comment by Micro-sheep** [comment]
> > 虽然大多数都还有好几年，但也有快到期的。。比如[https://xueqiu.com/S/SZ123007](https://xueqiu.com/S/SZ123007)
> > 
> > 看这个库用的都是东财源，东财的确是没有这一项。。雪球的有（集思录有登陆限制），
> > 
> > (https://xueqiu.com/hq#exchange=CN&industry=4_0&firstName=4)
> > 
> > 不知道方不方便爬。。我水平实在有限。还是通过tqsdk接触python的，还不到1年。。
> 
> 可以，我单独帮你爬一下吧。这个好的话后续可以加到 efinance 里面。

我看了一下，东方财富上面也有可转债到期日，下次版本更新的时候我再加上去吧。

**Comment by cczxxc** [comment]
> > > 虽然大多数都还有好几年，但也有快到期的。。比如https://xueqiu.com/S/SZ123007
> > > 看这个库用的都是东财源，东财的确是没有这一项。。雪球的有（集思录有登陆限制），
> > > (https://xueqiu.com/hq#exchange=CN&industry=4_0&firstName=4)
> > > 不知道方不方便爬。。我水平实在有限。还是通过tqsdk接触python的，还不到1年。。
> > 
> > 
> > 可以，我单独帮你爬一下吧。这个好的话后续可以加到 efinance 里面。
> 
> 我看了一下，东方财富上面也有可转债到期日，下次版本更新的时候我再加上去吧。

好的啊，原来还是隐藏属性呢哈哈

**Comment by Micro-sheep** [comment]
> 虽然大多数都还有好几年，但也有快到期的。。比如[https://xueqiu.com/S/SZ123007](https://xueqiu.com/S/SZ123007)
> 
> 看这个库用的都是东财源，东财的确是没有这一项。。雪球的有（集思录有登陆限制），
> 
> (https://xueqiu.com/hq#exchange=CN&industry=4_0&firstName=4)
> 
> 不知道方不方便爬。。我水平实在有限。还是通过tqsdk接触python的，还不到1年。。
刚更新版本，目前最新为 v0.2.9。更新之后即可获取可转债更多字段，具体见 README.md 的 Bond 部分示例代码。

**Comment by cczxxc** [comment]
> > 刚更新版本，目前最新为 v0.2.9。更新之后即可获取可转债更多字段，具体见 README.md 的 Bond 部分示例代码。

收到了，谢谢。
东财的似乎包括了很多早就退市的。我自己根据到期日期筛选一下就可以了。没问题了
