### ISSUE TITLE
Failed to establish a new connection: [Errno 111] Connection refused',)))

### ISSUE THREAD

**Issue by Note-Liu** [Micro-sheep/efinance#70]
, line 86, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 111] Connection refused

During handling of the above exception, another exception occurred: 
self, "Failed to establish a new connection: %s" % e
urllib3.exceptions.NewConnectionError: <urllib3.connection.HTTPSConnection object at 0x7fd7772d7e48>: Failed to establish a new connection: [Errno 111] Connection refused
.......
r = adapter.send(request, **kwargs)
  File "/home/l/.local/lib/python3/site-packages/requests/adapters.py", line 510, in send
    raise ProxyError(e, request=request)
requests.exceptions.ProxyError: HTTPSConnectionPool(host='push2his.eastmoney.com', port=443): Max retries exceeded with url: /api/qt/stock/kline/get?fields1=f1%2Cf2%2Cf3%2Cf4%2Cf5%2Cf6%2Cf7%2Cf8%2Cf9%2Cf10%2Cf11%2Cf12%2Cf13&fields2=f51%2Cf52%2Cf53%2Cf54%2Cf55%2Cf56%2Cf57%2Cf58%2Cf59%2Cf60%2Cf61&beg=19000101&end=20500101&rtntype=6&secid=1.600519&klt=101&fqt=1 (Caused by ProxyError('Cannot connect to proxy.', NewConnectionError('<urllib3.connection.HTTPSConnection object at 0x7fe2b3a6de48>: Failed to establish a new connection: [Errno 111] Connection refused',)))

请问这种情况是什么原因导致的？

**Comment by Micro-sheep** [comment]
你应该是开了网络代理或者本身在使用非国内的网络。需要使用国内的网络以保证稳定性。

**Comment by Note-Liu** [comment]
> 你应该是开了网络代理或者本身在使用非国内的网络。需要使用国内的网络以保证稳定性。

Thx.
