### ISSUE TITLE
获取多只股票是历史日K线数据，进度条走完，卡主不动

### ISSUE THREAD

**Issue by weills** [Micro-sheep/efinance#8]
您好，如题，在进度条走完（Processing 100%）之后，便卡住不动

**Comment by weills** [comment]
> 您好，如题，在进度条走完（Processing 100%）之后，便卡住不动

已解决，传入的list中的元素必须是str类型才行，否则便会卡住，但没有报错

**Comment by Micro-sheep** [comment]
> > 您好，如题，在进度条走完（Processing 100%）之后，便卡住不动
> 
> 
> 
> 已解决，传入的list中的元素必须是str类型才行，否则便会卡住，但没有报错

好的 谢谢反馈，我回头优化一下。
