### ISSUE TITLE
涨停跌停数据获取

### ISSUE THREAD

**Issue by Phimos** [Micro-sheep/efinance#93]
涨停 https://quote.eastmoney.com/ztb/detail#type=zbgc
跌停 https://quote.eastmoney.com/ztb/detail#type=dtgc
请问能否获取这两个页面的数据

**Comment by Micro-sheep** [comment]
> 涨停 https://quote.eastmoney.com/ztb/detail#type=zbgc
> 
> 跌停 https://quote.eastmoney.com/ztb/detail#type=dtgc
> 
> 请问能否获取这两个页面的数据

参考这里：https://github.com/Micro-sheep/efinance/issues/52
