### ISSUE TITLE
收盘后调用函数get_quote_history获取当日历史分钟数据返回Http status 204

### ISSUE THREAD

**Issue by raymomd** [Micro-sheep/efinance#98]
首先感谢大佬的无私奉献和辛苦耕耘！

现在的问题是今天收盘后调用函数get_quote_history获取当日的或者前几日的历史分钟数据返回Http status 204。今天才出现的问题，之前都一切正常。之前只有在没有数据的情况下才会收到204例如调用这个函数去获取休市当天的历史数据。

感谢大佬的帮助先。

**Comment by Micro-sheep** [comment]
我刚刚试了一下，暂时无法复现你说的这个问题，你提供一下关于测试环境的一些说明？比如电脑系统、Python 版本、efinance 版本、使用的网络情况（国内还是国外的网络）等。

**Comment by raymomd** [comment]
感谢大佬的即时反馈。问题已经解决。是我的疏忽，给错交易日期了。函数运行一切正常。
